### ISSUE TITLE
GradYear should be required on registration

### ISSUE THREAD

**Issue by JSlote** [CarletonDevX/textbook-exchange#66]
I think leftover listings from graduated students will become a problem pretty quickly, so it makes sense to collect gradYear info ASAP so we can do cleaning when necessary. To fix this I think we'll need to

- [x] Make grad year required on the backend (with David's fancy validation)
- [ ] Add a grad year requirement on the registration view--Duo, would you be willing to do this?

**Comment by dpikt** [comment]
Let's add this work to the dpikt/refactor-models branch before merging it #68

**Comment by taoduo** [comment]
I pushed a commit and added the input box. I just made the input box a text input so I think grad year needs validation on the backend. Now when I enter invalid year like "abcd", it can return a status of 400 and a messge like "invalid grad year".

 By the way, I also changed the gradYEar to gradYear since I think it is a typo. Is it?

**Comment by dpikt** [comment]
Yes that's definitely a typo! For the input, I was thinking it would be easier just to have a dropdown with the acceptable values - 2015-2020 currently. Later on we can make it fetch those from the backend but you can just hard-code them for now.

**Comment by taoduo** [comment]
I changed to a drop down. It seems to be working functionally.

**Comment by dpikt** [comment]
Looks great!
